
`fetch` 함수는 `XMLHttpRequest` 객체와 마친가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다. fetch 함수는 XMLHttpRequest 객체보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다. 인터넷 익스플로러를 제외한 대부분의 브라우저에서 제공한다.

```
fetch('https://jsonplaceholder.typicode.com/todos/1')
	.then(response => console.log(response));
```

`fetch` 함수는 HTTP 응답을 나타내는 `Response` 객체를 래핑한 `Promise` 객체를 반환한다.

![[Pasted image 20240218185112.png]](images/Pasted%20image%2020240218185112.png)

`fetch` 함수를 사용할 때는 에러 처리에 주의해야 한다. 다음 예제를 살펴보자.

```
fetch('https://jsonplaceholder.typicode.com/xxx/1') // 부적절한 URL
    .then(() => console.log('ok'))
    .catch(() => console.log('error'));
```

![[Pasted image 20240218190820.png]](images/Pasted%20image%2020240218190820.png)

부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생하고 catch 후속 처리가 될 것 같지만 `ok` 가 출력된다.

`fetch` 함수가 반환하는 프로미스는 기본적으로 404, 500 같은 HTTP 에러가 발생해도 에러를 `reject` 하지 않고 불리언 타입의 `ok` 상태를 `false` 로 설정한 `Response` 객체를 `resolve` 한다.

오프라인 등의 네트워크 장애나 CORS 에러의 의해 요청이 완료되지 못한 경우에만 프로미스를 `reject` 한다.

따라서 `fetch` 함수를 사용할 때는 다음과 같이 `fetch` 함수가 반환한 프로미스가 `reslove` 한 불리언 타입의 ok 상태를 확인해 명시적으로 에러를 처리해야 한다.

```
fetch('https://jsonplaceholder.typicode.com/xxx/1')
    .then(response => {
        if(!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todo => console.log(todo))
    .catch(err => console.log(err));
```

참고로 `axios` 는 모든 HTTP 에러를 `reject` 하는 프로미스를 반환한다. 따라서 모든 에러를 `catch` 에서 처리할 수 있어 편리하다. 또한 `axios` 는 인터셉터, 요청 설정 등 `fetch` 보다 다양한 기능을 지원한다.
